export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";
export const GET_ALL_EMPLOYEES = "GET_ALL_EMPLOYEES";
export const GET_EMPLOYEE_BY_ID = "GET_EMPLOYEE_BY_ID";
